export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const FETCH_ROBOTS_START = 'FETCH_ROBOTS_START';
export const FETCH_ROBOTS_SUCCESS = 'FETCH_ROBOTS_SUCCESS';
export const FETCH_ROBOTS_FAIL = 'FETCH_ROBOTS_FAIL';